Make brutes optionals
Zenoo/labrute pull request #1073
Opened 2024-12-06 16:59 UTC by YouriDK

2025-01-13 23:53 UTC, Zenoo commented
@YouriDK I'm going through all the PRs open here, since I finally have some time for them.
Could you please resolve the conflicts here?

2025-01-14 00:16 UTC, Zenoo requested changes

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/TournamentView.tsx
> +    if (fight.brute1 && fight.brute1.id !== brute.id && fight.brute2?.id !== brute.id) return;
```suggestion
    if (fight.brute1?.id !== brute.id && fight.brute2?.id !== brute.id) return;
```

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/TournamentView.tsx
> +                    const brute2 : Fighter | undefined = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'R');
It's always better to not force any typings, as they are already set.

```suggestion
                    const brute1 = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'L');
                    const brute2 = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'R');
```

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/clan/ClanForumView.tsx
> +                          <Text bold>{thread.creator?.name}</Text>
Add a fallback to `t('deleted')`, so that the space isn't just empty instead

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/clan/ClanForumView.tsx
> +                      <TableCell align="right">{thread.posts[0]?.author?.name}, {moment.utc(thread.updatedAt).format('HH:mm')}</TableCell>
Add a fallback

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/clan/ClanThreadView.tsx
>                      </Link>
Only add the link if the author exists, otherwise, only display a fallback instead of his name, and no link

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/clan/ClanView.tsx
> +                          <TableRow key={damages.brute?.id}>
React keys should never be the same, it will fail here if two brutes were deleted in the same clan.
Instead, you can simply filter the boss damages from deleted brute, both here and in the backend, to be sure

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/mobile/TournamentMobileView.tsx
> +                  const brute2 : Fighter | undefined = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'R');
```suggestion
                  const brute1 = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'L');
                  const brute2 = fighters.find((fighter) => !fighter.master && fighter.type === 'brute' && fighter.team === 'R');
```

2025-01-14 00:16 UTC, Zenoo commented on client/src/views/mobile/TournamentMobileView.tsx
> +                          {brute1 && <BruteRender brute={brute1 as BruteForRender} />}
It's better to avoid using `as` in TS, as it removes the type safety. If your brute1 object has all the fields necessary for <BruteRender />, it shouldn't be needed

2025-01-14 00:16 UTC, Zenoo commented on server/prisma/migrations/20241206164854_optional_brute/migration.sql
I'm confused here, `SET NOT NULL` will do the exact opposite to what we want, won't it?
It should be `DROP NOT NULL`, if I'm not mistaken.

2025-01-18 23:19 UTC, Zenoo requested changes

2025-01-18 23:19 UTC, Zenoo commented on client/src/views/clan/ClanThreadView.tsx
> +                      <Box component="img" src={`/images/rankings/lvl_${post.author?.ranking}.webp`} sx={{ mr: 1, width: 20 }} />
This will render a broken image if the author was deleted

2025-01-18 23:19 UTC, Zenoo commented on client/src/views/clan/ClanView.tsx
> +                          (damage) => damage.brute?.id !== undefined
```suggestion
                          (damage) => damage.brute
```

2025-01-18 23:19 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +            (damage) => damage.brute?.id !== undefined,
```suggestion
            (damage) => damage.brute
```

2025-01-19 09:13 UTC, YouriDK commented on client/src/views/clan/ClanThreadView.tsx
> +                      <Box component="img" src={`/images/rankings/lvl_${post.author?.ranking}.webp`} sx={{ mr: 1, width: 20 }} />
If there is a default image we can display, can you tell me so I'll put it

2025-01-19 09:37 UTC, Zenoo approved these changes
Thanks for your work, everything seems good !

2025-01-19 09:37 UTC, merged