Add more infos in Error
Zenoo/labrute pull request #1083
Opened 2024-12-30 11:17 UTC by YouriDK

Error type in typescript doesn't have error code, so you cannot be more specific in every areas , but with the prisma error you can add more detail

2024-12-30 11:57 UTC, Zenoo requested changes
I absolutely do not want DB errors to be shown to users.
This is not the modifications I had in mind.
The generic errors should still be shown to users, but the thrown errors should be more accurate, under the hood.

This issue has to be solved by creating a new error class for each error code, like `UnauthorizedError`, `TooManyRequestsError`, `GoneError`, etc etc ... All of those should be treated like `ExpectedError` is treated right now, meaning they won't generate a log, as they are planned errors.
These error should then be thrown in every controller instead of ExpectedError or Error where needed.

You can check all available error codes here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses

2024-12-30 14:27 UTC, YouriDK commented
ExpectedError is empty , the link you gave me is based on the statuscode which doesn't exist in the type Error. Could you give me an example ( for the 404 ) of what do you have in mind ? unless you don't want something generic in sendError but want something specific in each function ?

2024-12-30 14:38 UTC, Zenoo commented
It needs to be done in every controller method.
For example:
```ts
if (!brute1) {
  throw new ExpectedError(translate('bruteNotFound', user));
}
```
Will become
```ts
if (!brute1) {
  throw new NotFoundError(translate('bruteNotFound', user));
}
```

And in `sendError`, you need to adjust the conditions to not log the error on Discord if it's an instance of NotFoundError, since it was an ExpectedError before the change.
You also need to set the correct error code in `sendError` depending on the instance of the error thrown

2024-12-31 16:49 UTC, YouriDK commented
I did the changes base upon the initial code in sendErrors, if you disagree with the definition of statuscode, you'll have to highlight me on how I define them because status code is not a part of the Error type in typescript

2025-01-01 09:25 UTC, Zenoo commented
Your PR is not up to date

2025-01-01 18:35 UTC, Zenoo commented
I don't understand, your modifications do not change the returned error from the controllers, like I explained in the previous message

2025-01-01 18:38 UTC, YouriDK commented
Because I'm currently struggling with the merge 🥲, I didn't realise my branch was so faar back ( April 2024) , my modifications are not there yet , the compile command is showing errors that I'm fixing file by file :) , I'm on it

2025-01-01 18:50 UTC, YouriDK commented
@Zenoo  Should be better now :)

2025-01-01 19:14 UTC, Zenoo requested changes
There's no need to force type message to string, as it's already inferred from its default value.

I think you messed something up in the merge

core/src/index.ts and server/src/controllers/Achievements.ts for example

2025-01-01 19:14 UTC, Zenoo commented on core/src/errors/ExpectedError.ts
> +  constructor(message : string = '') {
```suggestion
  constructor(message = '') {
```

2025-01-01 19:14 UTC, Zenoo commented on core/src/errors/ForbiddenError.ts
> +  constructor(message : string = '') {
```suggestion
  constructor(message = '') {
```

2025-01-01 19:14 UTC, Zenoo commented on core/src/errors/NotFoundError.ts
> +  constructor(message :string = '') {
```suggestion
  constructor(message = '') {
```

2025-01-01 19:14 UTC, Zenoo commented on core/src/index.ts
Some exports have been changed here, they should be reverted

2025-01-01 19:37 UTC, YouriDK commented on core/src/index.ts
You mean some of them are wrong ? I changed some of them like those  import { colors } from './brute/colors'; because they didn't work otherwise, or you mean on the eslint/prettier part ?

2025-01-01 23:17 UTC, Zenoo commented on core/src/index.ts
What do you mean they didn't work? Exporting directly with `export * from '...';` allows to export everything from a file instead of having to manually export every method/const when you add one, which is why it's better to use export from.

Here for example, `export * from './brute/colors';` is working perfectly right now, so it should work for you too without needing to import/export it manually

2025-01-01 23:19 UTC, Zenoo requested changes

2025-01-01 23:19 UTC, Zenoo commented on server/src/utils/clan/updateClanPoints.ts
> +import { getBruteGoldValueFromLevel, getBruteGoldValueFromRanking } from '@labrute/core/src/brute/getBruteGoldValue.js';
Also, this is not the correct way to import from core, it should be the same as before, @labrute/core

2025-01-03 13:13 UTC, YouriDK commented on core/src/index.ts
Here the issue I have with colors 
![image](https://github.com/user-attachments/assets/08e6c7f2-7777-4aac-92fc-352d4c87496d)
 Same issue for this one : 
![image](https://github.com/user-attachments/assets/6250ef0f-df46-4118-bed0-8fc223a2c29e)
I checked the index.ts in /core but I didn't see anything ( I already compile like you proposed on the discord )

2025-01-03 13:18 UTC, Zenoo requested changes

2025-01-03 13:18 UTC, Zenoo commented on core/src/index.ts
I'm pretty sure you don't have the correct core/index.ts file to begin with, and the version you worked on was outdated.
Please try from a clean branch, forking from the current project, to see if you still have these issues, as they don't exist currently.
If you don't, then add your modifications on top

2025-01-03 15:47 UTC, YouriDK commented
@Zenoo  I think we're good

2025-01-03 23:23 UTC, Zenoo requested changes
Could you explain which differences you see between a LimitError and a ForbiddenError?
I switched some of them in the review, since they didn't seem right to me, but that may be because we don't have the same definition for it.
(If you feel like some of my switches are not accurate, don't switch them, but I'm curious why you choose one of the error types over the other)

2025-01-03 23:23 UTC, Zenoo commented on core/src/errors/NotFoundError.ts
> +  constructor(message :string = '') {
```suggestion
  constructor(message = '') {
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('cannotSacrificeSameDay', authed));
This seems like a LimitError would be better suited here, as Forbidden is mostly used elsewhere when a permission is not granted.

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('favoriteLimitReached', authed));
```suggestion
        throw new LimitError(translate('favoriteLimitReached', authed));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('nameContainsBannedWord', authed));
```suggestion
        throw new LimitError(translate('nameContainsBannedWord', authed));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('nameAlreadyTaken', authed));
```suggestion
        throw new LimitError(translate('nameAlreadyTaken', authed));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/ClanWars.ts
> +        throw new ForbiddenError(translate('cantFightOwnClan', user));
```suggestion
        throw new LimitError(translate('cantFightOwnClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/ClanWars.ts
> +        throw new ForbiddenError(translate('opponentWarOngoing', user));
```suggestion
        throw new LimitError(translate('opponentWarOngoing', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('alreadyInClan', user));
```suggestion
        throw new LimitError(translate('alreadyInClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('clanNameAlreadyTaken', user));
```suggestion
        throw new LimitError(translate('clanNameAlreadyTaken', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('nameContainsBannedWord', user));
```suggestion
        throw new LimitError(translate('nameContainsBannedWord', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('alreadyInClan', user));
```suggestion
        throw new LimitError(translate('alreadyInClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('alreadyRequested', user));
```suggestion
        throw new LimitError(translate('alreadyRequested', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('alreadyInClan', user));
```suggestion
        throw new LimitError(translate('alreadyInClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +          throw new ForbiddenError(translate('masterCannotLeave', user));
```suggestion
          throw new LimitError(translate('masterCannotLeave', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Clans.ts
> +        throw new ForbiddenError(translate('notYourClan', user));
```suggestion
        throw new LimitError(translate('notYourClan', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Configs.ts
> +        throw new ForbiddenError('CRYPTR_SECRET already exists');
```suggestion
        throw new LimitError('CRYPTR_SECRET already exists');
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Configs.ts
> +        throw new ForbiddenError('CRYPTR_SECRET cannot be deleted');
```suggestion
        throw new LimitError('CRYPTR_SECRET cannot be deleted');
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Fights.ts
> +        throw new ForbiddenError('Fight unavailable for now');
```suggestion
        throw new LimitError('Fight unavailable for now');
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Tournaments.ts
> +        throw new ForbiddenError(translate('rankUpBeforeTournament', user));
```suggestion
        throw new LimitError(translate('rankUpBeforeTournament', user));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Users.ts
> +        throw new ForbiddenError(translate('userAlreadyBanned', authed));
```suggestion
        throw new LimitError(translate('userAlreadyBanned', authed));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/controllers/Users.ts
> +        throw new ForbiddenError(translate('userNotBanned', authed));
```suggestion
        throw new LimitError(translate('userNotBanned', authed));
```

2025-01-03 23:23 UTC, Zenoo commented on server/src/utils/fight/generateFight.ts
> +    throw new ForbiddenError('Attempted to created a fight between the same brutes');
```suggestion
    throw new LimitError('Attempted to created a fight between the same brutes');
```

2025-01-04 16:47 UTC, YouriDK commented
To me FobiddenError is when you do something you are not supposed to do , LimitError is when you do something you usually can do but you reached the limit like the number of brutes in the clan. I let Excpected Error when they didn't feel fitting in those

2025-01-04 16:49 UTC, YouriDK commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('cannotSacrificeSameDay', authed));
I put ForbiddenError because it's something you cannot do. It's not like you can do it once , you just cannot ^^

2025-01-04 16:51 UTC, YouriDK commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('nameContainsBannedWord', authed));
Same here , it's not about a amount of banned words, you just cannot

2025-01-04 16:51 UTC, YouriDK commented on server/src/controllers/Brutes.ts
> +        throw new ForbiddenError(translate('nameAlreadyTaken', authed));
Same vision : if you cannot do it at least once it's Forbidden then

2025-01-04 16:53 UTC, YouriDK commented on server/src/controllers/Fights.ts
> +        throw new ForbiddenError('Fight unavailable for now');
This one both fits , because it's not about the action but more of the timing 🤔

2025-01-04 16:53 UTC, YouriDK commented on server/src/controllers/Tournaments.ts
> +        throw new ForbiddenError(translate('rankUpBeforeTournament', user));
Same vision as before

2025-01-04 16:54 UTC, YouriDK commented on server/src/controllers/Users.ts
> +        throw new ForbiddenError(translate('userAlreadyBanned', authed));
Oh on this one  tho yeah Limit fit better

2025-01-04 16:55 UTC, YouriDK commented on server/src/controllers/Users.ts
> +        throw new ForbiddenError(translate('userNotBanned', authed));
Same vision

2025-01-04 16:56 UTC, YouriDK commented on server/src/utils/fight/generateFight.ts
> +    throw new ForbiddenError('Attempted to created a fight between the same brutes');
Same vision , same brutes fight are forbidden

2025-01-04 17:05 UTC, YouriDK commented on server/src/controllers/Configs.ts
> +        throw new ForbiddenError('CRYPTR_SECRET already exists');
Limit can fit on this one

2025-01-13 23:55 UTC, Zenoo approved these changes
Everything seems in order, thanks for your work !

2025-01-13 23:56 UTC, merged